### ISSUE TITLE
Exports za 2017 i 2018

### ISSUE THREAD

**Issue by mravko** [jovanovski/AirCare_Exports#1]
Zdravo @jovanovski.

Dali moze da gi kacis i exportite za 2017 (a nabrzo i za 2018)? Fala.

**Comment by jovanovski** [comment]
Здраво Марко,

Ќе се обидам викендов да ги спремам :)

**Comment by jovanovski** [comment]
Export за 2017 е додаден, за 2018 ќе го додадам во Јануари :)
